source 'https://rubygems.org'

gem "jekyll", "~> 4.3.2"
gem "just-the-docs", "0.7.0"  # Add the theme explicitly
gem "jekyll-seo-tag"

# Add missing gems for Ruby 3.4.0+ compatibility
gem "csv"
gem "logger"
gem "ostruct"
gem "base64"

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]